Update Apps docker dev environment to use Apps plugin 1.2 and server 7.6
mattermost/mattermost-app-examples pull request #10
Opened 2022-12-19 10:44 UTC by javaguirre

#### Summary

Update Apps 1.2.0 MM 7.4.0

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-43196

2022-12-20 13:16 UTC, levb approved these changes

2022-12-20 21:30 UTC, azigler approved these changes
@javaguirre Thanks for doing this -- can we go ahead and merge?

2022-12-21 06:54 UTC, hanzei requested changes

2022-12-21 06:54 UTC, hanzei commented on docker-compose.yml
> +    image: "mattermost/mattermost-enterprise-edition:7.4.0" # https://hub.docker.com/r/mattermost/mattermost-enterprise-edition/tags
Should we go to 7.5 directly?

2022-12-21 08:22 UTC, javaguirre commented on docker-compose.yml
> +    image: "mattermost/mattermost-enterprise-edition:7.4.0" # https://hub.docker.com/r/mattermost/mattermost-enterprise-edition/tags
sure, why not?

2022-12-21 08:26 UTC, javaguirre commented
> @javaguirre Thanks for doing this -- can we go ahead and merge?

we haven't cut the v1.2 of the apps framework yet, that's why I put it as Draft. I'd like to test it when we do, shouldn't be a problem, but just in case. :-)

2023-01-02 23:03 UTC, hanzei requested changes
Two question:

1. Should other version numbers like https://github.com/mattermost/mattermost-app-examples/blob/be70ed24d88cbd1f0cd333e0bb0fcdfdbb8405d9/golang/webhooks/hello.go#L27 also get updated?
2. Should the `go.mod` files get updated to import `v1.2.0` of github.com/mattermost/mattermost-plugin-apps?

2023-01-03 08:45 UTC, javaguirre commented
> Two question:
> 
> 1. Should other version numbers like https://github.com/mattermost/mattermost-app-examples/blob/be70ed24d88cbd1f0cd333e0bb0fcdfdbb8405d9/golang/webhooks/hello.go#L27
>     also get updated?
> 2. Should the `go.mod` files get updated to import `v1.2.0` of github.com/mattermost/mattermost-plugin-apps?

Yes, let's do that once we cut the release 👌

2023-01-08 16:42 UTC, dsharma522 commented
Please consider mm-server version to [7.1.5](https://github.com/mattermost/mattermost-server/releases/tag/v7.1.5)

2023-01-09 13:09 UTC, hanzei commented
@dsharma522 Why should the version to changed to 7.1.5, then 7.6 is the newer release?

2023-01-09 14:06 UTC, levb commented
@dsharma522 *7.5* is the correct version, and that's what's in the PR.

2023-01-10 09:45 UTC, javaguirre commented
I'm getting an error with these versions, checking out what is happening.
![Screenshot 2023-01-10 at 10 45 06](https://user-images.githubusercontent.com/488556/211517217-1e6e47e4-28dd-4f54-92eb-514a0127a8cf.png)

2023-01-10 09:53 UTC, javaguirre commented
![Screenshot 2023-01-10 at 10 53 02](https://user-images.githubusercontent.com/488556/211518961-5c3c88e7-ca6c-42b1-8bab-0b528702a98b.png)

2023-01-10 11:11 UTC, javaguirre commented
I see we need to have it in the marketplace to finish testing this.

![Screenshot 2023-01-10 at 12 10 44](https://user-images.githubusercontent.com/488556/211536297-ea0a7ffa-9968-4374-b9d7-c17ba787003f.png)

2023-01-19 21:53 UTC, azigler commented
@javaguirre Are we ready to revisit this PR now?

2023-01-20 08:16 UTC, javaguirre commented
Hey @azigler ! Waiting on this https://github.com/mattermost/mattermost-marketplace/pull/331

2023-01-26 12:11 UTC, hanzei requested changes
The version number in https://github.com/mattermost/mattermost-app-examples/blob/be70ed24d88cbd1f0cd333e0bb0fcdfdbb8405d9/golang/serverless/manifest.json#L3 also should get updated

2023-01-27 08:28 UTC, javaguirre commented
Done

2023-01-31 10:44 UTC, hanzei approved these changes
LGTM :rocket:

2023-01-31 18:18 UTC, merged